module.exports = {
  PROMOCODE: 'PROMOCODE',
  P2P_TRANSFER: 'P2P_TRANSFER',
  TED_CASH_IN: 'TED_CASH_IN',
  PAYMENT_SLIP_CASH_IN: 'PAYMENT_SLIP_CASH_IN',
  DEPOSIT: 'DEPOSIT',
  WITHDRAWAL: 'WITHDRAWAL',
  BANK_CASH_OUT: 'BANK_CASH_OUT',
  CANCELLATION_BANK_CASH_OUT: 'CANCELLATION_BANK_CASH_OUT',
  PAYMENT_BILL_CASH_OUT: 'PAYMENT_BILL_CASH_OUT',
  PAYMENT_QR_CODE: 'PAYMENT_QR_CODE',
  PAYMENT_TOPUP: 'PAYMENT_TOPUP',
};

